# the compiler: gcc for C program, define as g++ for C++
CC = gcc

# compiler flags:
#  -g    adds debugging information to the executable file
#  -Wall turns on most, but not all, compiler warnings
CFLAGS  = -g -ansi -Wall -m32

# the build target executable:
TARGET = test3
TARGET1 = frac_heap

all: $(TARGET)

$(TARGET): $(TARGET).c
	$(CC) $(CFLAGS) $(TARGET).c $(TARGET1).c -o $(TARGET).out 

clean:
	$(RM) $(TARGET)