CC = g++
CFLAGS = -ansi -Wall
TARGET = Proj3
TARGET2 = Proj3Aux
TARGET3 = Fraction



all: Proj3
Proj3: Proj3.cpp
	$(CC) $(CFLAGS) $(TARGET).cpp $(TARGET2).cpp $(TARGET3).cpp -o $(TARGET).out
clean:
	$(RM)$(TARGET)