CC = g++
CFLAGS = -ansi -Wall
TARGET = Proj2
TARGET2 = Blackjack
TARGET3 = Player
TARGET4 = Hand
TARGET5 = Deck
TARGET6 = Card


all: Proj2
Proj2: Proj2.cpp
	$(CC) $(CFLAGS) $(TARGET).cpp $(TARGET2).cpp $(TARGET3).cpp $(TARGET4).cpp $(TARGET5).cpp $(TARGET6).cpp -o $(TARGET).out
clean:
	$(RM)$(TARGET)